package DB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.Date;  
import java.sql.*;

import Modelo.Compra;
import Modelo.Producto;
import Modelo.LineaProducto;

public class DBLineaCarro extends DBAdapter 
{
	DBProductos proddb;
		
	/*public void CreaLineaCarro(LineaProducto lp)
	{
		try
		{
		Statement st=conex.createStatement();
		
st.execute("INSERT INTO lineaCarro(codigo_producto,codigo_carro) VALUES('"+lp.getProducto().getCodigo()+"','"+lp.getCodC()+"')");


	} catch (SQLException t) 
		{
		
		t.printStackTrace();
	
		}	
	}*/
	
	public LineaProducto CreaLineaCarro(LineaProducto linea)
	{
		
				
		try {
		
			PreparedStatement preparedStatement = conex.prepareStatement("insert into lineaCarro(codigo_producto) values (?)",PreparedStatement.RETURN_GENERATED_KEYS);
            
            preparedStatement.setFloat(1, linea.getProducto().getCodigo());
            preparedStatement.executeUpdate();
            
            ResultSet tableKeys = preparedStatement.getGeneratedKeys();
            tableKeys.next();
            
            
            int autoGeneratedID = tableKeys.getInt(1);
           
            linea.setCodC(autoGeneratedID);
            return linea;
			
		} catch (SQLException sqle) 
		{
			sqle.printStackTrace();
		}
		return linea;
	}
	
	
	
	public ArrayList<LineaProducto> buscaLineas(String codCarro)
	{
		LineaProducto lp=null;
		ArrayList<LineaProducto> ProductosCarro=new ArrayList<LineaProducto>();
		Producto prod;
		try
		{
			proddb=new DBProductos();
		Statement st=conex.createStatement();
		ResultSet rs=st.executeQuery("SELECT * FROM lineaCarro where codigo_carro='"+codCarro+"')");
		while(rs.next())
		{
		
			lp=new LineaProducto();
			lp.setCodC(rs.getInt("codigo_carro"));
			prod=proddb.buscaProducto(rs.getInt("codigo_producto"));
			lp.setProducto(prod);
			ProductosCarro.add(lp);
			
		}

		return ProductosCarro;
	} catch (SQLException t) 
	{
		
	t.printStackTrace();
	return ProductosCarro;
	}
		
		
	}
}